CREATE TABLE "Наряд-задание" (
	"taskNumber"	TEXT,
	"brigadeCode"	TEXT,
	"dealNumber"	TEXT,
	"productCode"	TEXT,
	"date"	TEXT,
	"operationCode"	TEXT,
	"operationName"	TEXT,
	"professionCode"	TEXT,
	"rank"	INTEGER,
	"grid"	TEXT,
	"unity"	INTEGER,
	"operationTime"	INTEGER,
	"rate"	INTEGER,
	"detailsPlan"	INTEGER,
	"detailsResult"	INTEGER,
	PRIMARY KEY("taskNumber", "productCode", "operationCode"),
	FOREIGN KEY("productCode","operationCode") REFERENCES "Справочник видов операций"("productCode","operationCode"),
	FOREIGN KEY("rank") REFERENCES "Список разрядов"("rank"),
	FOREIGN KEY("grid") REFERENCES "Список сеток"("grid"),
	FOREIGN KEY("brigadeCode","dealNumber") REFERENCES "План работы бригад швейного цеха"("brigadeCode","dealNumber")
);