from .main import BaseRecord, BaseDataBaseView
from .brigade_plan import BrigadePlanElement, BrigadePlan
from .brigades_list import BrigadeElement, BrigadesList
from .clients_list import ClientElement, ClientsList
from .grid_list import GridElement, GridList
from .operations_list import OperationsElement, OperationsList
from .product_list import ProductElement, ProductList
from .rank_list import RankElement, RankList
from .task import TaskElement, Task
from .specification import SpecificationElement, Specification
from .task_report import ReportTaskElement, ReportTask
from .deal_report import ReportDealElement, ReportDeal
from .brigade_report import ReportBrigadeElement, ReportBrigade
